LM3.MVC.Factory/Models/ErrorViewModel.cs
namespace LM3.MVC.Factory.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

LM3.MVC.Factory/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using LM3.MVC.Factory.Models;

namespace LM3.MVC.Factory.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

LM3.MVC.Factory/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Api.Weather.Entities;
using Library.Request.Helper;
using Microsoft.AspNetCore.Mvc;


namespace LM3.MVC.Factory.Controllers
{
    public class WeatherController : Controller
    {
        public async Task<IActionResult> Index()
        {

            ViewBag.Msn = "hOLA MUNDO";


            IEnumerable<WeatherForecast> wea = await HttpRequestHelper.GetMethod<IEnumerable<WeatherForecast>>("MyCloudSchool", "/weatherforecast");

            if (wea !=null)
            {
                ViewBag.list = wea.ToList();
            }
            else
            {
                ViewBag.list = null;
            }

            return  View();
        }
    }
}

LM3.MVC.Factory/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LM3.MVC.Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LM3.MVC.Factory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LM3.MVC.Factory.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LM3.MVC.Factory</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Clima</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LM3.MVC.Factory - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LM3.MVC.Factory/Views/Weather/Index.cshtml
@using Api.Weather.Entities;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

    string msn = ViewBag.Msn;
    List< WeatherForecast> weathers = ViewBag.list;
}



<h1>Clima es:</h1>





<table>
           <thead>
               <tr>
                   <th>Fecha</th>
                   <th>Temperatura Cº</th>
                   <th>Temperatura Fº</th>
                   <th>Resumen:</th>
               </tr>
               

           </thead>

           <tbody>
               <tr>
                   @if (weathers != null)
                   {
                       @foreach (var weather in weathers)
                       {
                       <tr>
                           <td>@weather.Date</td>
                           <td>@weather.TemperatureC</td>
                           <td>@weather.TemperatureF</td>
                           <td>@weather.Summary</td>
                       </tr>
                      }
                   }
                   else
                   {
<td> No existen registros</td>
                }
               </tr>

           </tbody>

       </table>
            